import React from 'react'
import Head from 'next/head'
import '../styles/globals.scss'

const MyApp = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Aom Thanya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
